### ISSUE TITLE
Daily builds not populating for non-sponsor

### ISSUE THREAD

**Issue by KillYourFM** [elementary/builds#15]
## Prerequisites
- [ x] I have searched open and closed issues for duplicates.

## Describe the bug
Daily builds are not populating after having my username added to the "Allow" list by Dan, and after granting the app access via Github settings. 

### To Reproduce
1. Go to 'https://builds.elementary.io/
2. Click on 'Get Daily Builds'
3. Github logs you in, checks sponsorship level
4. "Get Daily Builds" is replaced by "Sponsor Elementary"

### Expected behavior
"Get Daily Builds" button produces list of eOS 6.0 dailies
### Screenshots or screen recordings
![eos daily buils](https://user-images.githubusercontent.com/47599547/89449675-b65f9500-d759-11ea-91b0-7a447a0d209c.png)

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by btkostner** [comment]
@KillYourFM Can you try now and let me know if that PR fixed your issue please

**Comment by KillYourFM** [comment]
That indeed fixed it, thank you.
