### ISSUE TITLE
Timestamps don't match what's in the filename

### ISSUE THREAD

**Issue by cassidyjames** [elementary/builds#22]
I assume the reason is "because timezones," but we should make sure the ISO filename and the listed build timestamp are assuming the same timezone so that the dates match up.

**Comment by btkostner** [comment]
What time zone are the isos dated in? I just used UTC for the time, because that's what I assumed: https://github.com/elementary/builds/blob/master/pages/downloads.vue#L125

**Comment by cassidyjames** [comment]
@btkostner they're UTC, but I think the issue is that JS is basically saying, "Midnight today in UTC was actually yesterday in your current timezone!" when what we actually want is to display the timestamps in UTC as well.
