### ISSUE TITLE
Explicit logout/way to clear cookies

### ISSUE THREAD

**Issue by cassidyjames** [elementary/builds#38]
I seem to be hitting issues where something (a cookie?) is caching the state of my access, meaning it takes a lot of hard refreshing to get things to change, i.e. when changing GitHub accounts, if sponsorship status changed, if org membership changed, or if I was added/removed from the allowlist. It might make sense to have an explicit "logout" action that clears that out, forces re-auth, and re-checks all the permissions?

**Comment by btkostner** [comment]
Do we know how we want this to look?

**Comment by cassidyjames** [comment]
@btkostner whoops, totally missed this issue. Derp. I think something like the sub-nav on developer.elementary.io works for me.

**Comment by rajkumaar23** [comment]
@cassidyjames I would like to work on this.
