### ISSUE TITLE
Release occasional “more stable” builds

### ISSUE THREAD

**Issue by danrabbit** [elementary/builds#49]
Okay so after a bunch of discussion it sounds like what we want to do here is create a new subscription service where folks can sign up for something like $10/yr to get access to daily images. We'd also allow anyone on elementary GitHub teams to log in and have access without a subscription.

Some things we need:

- [x] ~~A signup/login screen that allows GitHub login~~
- [ ] ~~A screen where you can manage your subscription including managing payment cards and cancelling your subscription~~ #50
- [x] ~~A way to present unstable/daily/edge images. These are images that are frequently broken and are the equivalent of running git master. Definitely not recommended for production machines. This is most useful for people who are working on elementary OS itself. We usually keep a backlog of a handful of these since they could potentially be completely broken an unusable on a day-to-day basis.~~
- [ ] A way to present "stable" beta images. These are images that are meant for 3rd party developers to build their apps on. They aren't release quality, but shouldn't be horrific to run. Probably still not recommended for production machines. There's probably only one of these at a time on the server.

**Comment by cassidyjames** [comment]
Gonna reduce this in scope since most is done and another is probably not needed.

Let's focus on getting the “stable” (beta? RC?) build sorted to close this out. Managing your sub can just be a link to a Sponsors page, most likely.

**Comment by btkostner** [comment]
@cassidyjames are we planning to create a new build with a new naming convention, or are we expecting to be able to promote existing builds? If we plan to promote, we will need some kind of persistence (database) which will complicate this a lot.

**Comment by cassidyjames** [comment]
@btkostner I'm totally fine doing it by filename, if that's easier. But I guess we'd need the ability to human-test that particular ISO before sending it to the builds server… so I'm open to options. @danrabbit might have thoughts, too.

**Comment by danrabbit** [comment]
@cassidyjames @btkostner Since we already have daily builds with the daily repo, I imagine we could do weekly (or something) builds with the stable repo for beta yeah?

**Comment by cassidyjames** [comment]
Now that the site pulls the latest stable ISO, I think this is done? We can kick off new stable ISOs in the OS repo and they'll show up here. Unless we want to make a new folder/naming scheme with weekly or something, but at that point we'll need to change things here and in the OS repo.

**Comment by danrabbit** [comment]
Ha yeah this is done. Go team lol
