### ISSUE TITLE
List Raspberry Pi builds

### ISSUE THREAD

**Issue by cassidyjames** [elementary/builds#55]
We now have RasPi builds merged into the OS project; we should get them listed here just like Pinebook Pro builds.

**Comment by btkostner** [comment]
At this point, I think we should list types up top in the subnav, or do a dropdown to select what ISO type. Listing all of them on one page is getting a little hard to navigate.

**Comment by cassidyjames** [comment]
@btkostner I agree that would be nice, but getting the builds up at all is a first step.
